[connections.supabase]
SUPABASE_URL = "https://dlxzibefzilpnoavemot.supabase.co"
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRseHppYmVmemlscG5vYXZlbW90Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ0ODU5NjEsImV4cCI6MjA2MDA2MTk2MX0.iKXrPL7ySQaKz67fs-H9tySIyTUQXVJ71k7sVjRlRuU"